// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpD4gykhvJCen_0p2P9arIq1hC1RHHte0',
    appId: '1:748635827007:web:7d2fde644ebe1a6426018a',
    messagingSenderId: '748635827007',
    projectId: 'atom8-1cbf2',
    authDomain: 'atom8-1cbf2.firebaseapp.com',
    storageBucket: 'atom8-1cbf2.firebasestorage.app',
    measurementId: 'G-T501P4H40S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5IHaXrQ48588QGlELwldLIhnBCTEV2kQ',
    appId: '1:748635827007:android:d33dec219a1e567e26018a',
    messagingSenderId: '748635827007',
    projectId: 'atom8-1cbf2',
    storageBucket: 'atom8-1cbf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo8wb3SsfdpH93IDVXXhR4RO_ZqEwFunk',
    appId: '1:748635827007:ios:ca912b35e3599f4726018a',
    messagingSenderId: '748635827007',
    projectId: 'atom8-1cbf2',
    storageBucket: 'atom8-1cbf2.firebasestorage.app',
    iosBundleId: 'dev.flutterexplained.webrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo8wb3SsfdpH93IDVXXhR4RO_ZqEwFunk',
    appId: '1:748635827007:ios:bf94089ae6c44c5926018a',
    messagingSenderId: '748635827007',
    projectId: 'atom8-1cbf2',
    storageBucket: 'atom8-1cbf2.firebasestorage.app',
    iosBundleId: 'dev.flutterexplained.webrtcTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpD4gykhvJCen_0p2P9arIq1hC1RHHte0',
    appId: '1:748635827007:web:44109ff5690b692326018a',
    messagingSenderId: '748635827007',
    projectId: 'atom8-1cbf2',
    authDomain: 'atom8-1cbf2.firebaseapp.com',
    storageBucket: 'atom8-1cbf2.firebasestorage.app',
    measurementId: 'G-M3HJMJTJ5L',
  );
}
